name = "pawdia-ai-api-service"
main = "../api/worker.js"
compatibility_date = "2025-12-26"
workers_dev = true
preview_urls = true
routes = ["pawdia-ai.com/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "pawdia-ai-db"
database_id = "e64c0539-0e91-42fb-a73b-df2803f31e82"
